version: "3"

services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
    #environment:
    # - PROJECT_NAME=backend
    #  - BACKEND_CORS_ORIGINS=http://localhost:8080
    #  - DATABASE_URL=postgres://hello_fastapi:hello_fastapi@db:5432/hello_fastapi_dev
    #  - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    # depends_on:
    #   - db

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    # command: 
    #   "yarn serve"
